"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Learn.py']
DATA_FILES = [
    'images',
    'defaults',
    'style.css']
OPTIONS = {
    'iconfile': 'images/Logo.png',
}
PACKAGES = [
    'gui',
    'classes'
]

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    packages=PACKAGES
)
